server:
  port: 8081
spring:
  application:
    name: movie
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3306/movies
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

info:
  version: @version@